#include "mediatek/custom/wt98518/cgen/cfgdefault/CFG_Audio_Default_Cust.h"
#include "mediatek/custom/wt98518/cgen/cfgdefault/CFG_Custom1_Default.h"
#include "mediatek/custom/wt98518/cgen/cfgdefault/CFG_GPS_Default.h"
#include "mediatek/custom/wt98518/cgen/cfgdefault/CFG_PRODUCT_INFO_Default.h"
#include "mediatek/custom/wt98518/cgen/cfgdefault/CFG_WIFI_Default.h"
